sonar.projectKey=threadpoint
sonar.projectName=threadpoint
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.
sonar.inclusions=**/*.go,go.mod
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,coverage.out,coverage-summary.txt,test-results.json,dist/**,.tmp/**
sonar.go.coverage.reportPaths=coverage.out
