// SPDX-License-Identifier: Apache-2.0
// Code generated by cli-help-flags.go; DO NOT EDIT.

package main

import "strings"

func helpScannerConsumesValue(arg string) bool {
	if !strings.HasPrefix(arg, "-") || strings.Contains(arg, "=") {
		return false
	}
	switch strings.TrimLeft(arg, "-") {
	case "backup", "backup-namespace", "channel", "classify", "confirm", "dir", "exclude-providers", "format", "home", "max-age", "providers", "repo", "root", "skip-dirs", "version":
		return true
	default:
		return false
	}
}
