// SPDX-License-Identifier: Apache-2.0
//go:build ignore

// cli-help-flags derives help-scanner option arity from command flag declarations.
// Run with -dir pointing to a CLI package. -check verifies the generated file;
// without it, the command replaces help_flags_generated.go in that directory.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	dir := flag.String("dir", ".", "CLI package directory")
	check := flag.Bool("check", false, "check instead of writing generated metadata")
	spdx := flag.String("spdx", "", "optional SPDX identifier for generated output")
	flag.Parse()
	if err := run(*dir, *check, *spdx); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(dir string, check bool, spdx string) error {
	files, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return err
	}
	var sources []*ast.File
	types := map[string]ast.Expr{}
	booleanTypes := map[string]bool{}
	for _, path := range files {
		if strings.HasSuffix(path, "_test.go") || strings.HasSuffix(path, "_generated.go") {
			continue
		}
		positions := token.NewFileSet()
		file, err := parser.ParseFile(positions, path, nil, 0)
		if err != nil {
			return err
		}
		if err := validateFlagSetNames(file, positions); err != nil {
			return err
		}
		sources = append(sources, file)
		ast.Inspect(file, func(node ast.Node) bool {
			switch node := node.(type) {
			case *ast.TypeSpec:
				types[node.Name.Name] = node.Type
			case *ast.FuncDecl:
				if node.Name.Name == "IsBoolFlag" && node.Recv != nil {
					receiver := node.Recv.List[0].Type
					if ptr, ok := receiver.(*ast.StarExpr); ok {
						receiver = ptr.X
					}
					if name, ok := receiver.(*ast.Ident); ok {
						booleanTypes[name.Name] = true
					}
				}
			}
			return true
		})
	}
	arities := map[string]bool{}
	for _, file := range sources {
		ast.Inspect(file, func(node ast.Node) bool {
			call, ok := node.(*ast.CallExpr)
			if !ok || err != nil {
				return true
			}
			selector, ok := call.Fun.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			receiver, ok := selector.X.(*ast.Ident)
			if !ok || receiver.Name != "fs" {
				return true
			}
			index, takesValue := 0, true
			switch selector.Sel.Name {
			case "String", "Int", "Int64", "Uint", "Uint64", "Float64", "Duration":
			case "Bool":
				takesValue = false
			case "Var":
				index = 1
				typ := expressionType(call.Args[0], types)
				if typ == "" {
					err = fmt.Errorf("cannot resolve custom flag type in %s", dir)
					return false
				}
				takesValue = !booleanTypes[typ]
			default:
				return true
			}
			literal, ok := call.Args[index].(*ast.BasicLit)
			if !ok || literal.Kind != token.STRING {
				err = fmt.Errorf("flag name must be a string literal in %s", dir)
				return false
			}
			name, parseErr := strconv.Unquote(literal.Value)
			if parseErr != nil {
				err = parseErr
				return false
			}
			if old, exists := arities[name]; exists && old != takesValue {
				err = fmt.Errorf("inconsistent arity for --%s", name)
				return false
			}
			arities[name] = takesValue
			return true
		})
	}
	if err != nil {
		return err
	}
	var names []string
	for name, value := range arities {
		if value {
			names = append(names, strconv.Quote(name))
		}
	}
	sort.Strings(names)
	var source bytes.Buffer
	if spdx != "" {
		fmt.Fprintf(&source, "// SPDX-License-Identifier: %s\n", spdx)
	}
	fmt.Fprintln(&source, "// Code generated by cli-help-flags.go; DO NOT EDIT.\n\npackage main\n\nimport \"strings\"")
	fmt.Fprintf(&source, "\nfunc helpScannerConsumesValue(arg string) bool {\nif !strings.HasPrefix(arg, \"-\") || strings.Contains(arg, \"=\") { return false }\nswitch strings.TrimLeft(arg, \"-\") {\ncase %s: return true\ndefault: return false\n}\n}\n", strings.Join(names, ", "))
	body, err := format.Source(source.Bytes())
	if err != nil {
		return err
	}
	path := filepath.Join(dir, "help_flags_generated.go")
	if check {
		existing, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !bytes.Equal(existing, body) {
			return fmt.Errorf("%s is stale; run go generate in the CLI package", path)
		}
		return nil
	}
	return os.WriteFile(path, body, 0o644)
}

// Flag registrations are scanned on fs; reject constructors and helper
// parameters that would silently escape that scan, including aliased imports.
func validateFlagSetNames(file *ast.File, positions *token.FileSet) error {
	flagPackage := ""
	for _, spec := range file.Imports {
		if spec.Path.Value == strconv.Quote("flag") {
			flagPackage = "flag"
			if spec.Name != nil {
				flagPackage = spec.Name.Name
			}
		}
	}
	allowed := make(map[ast.Expr]bool)
	ast.Inspect(file, func(node ast.Node) bool {
		switch node := node.(type) {
		case *ast.AssignStmt:
			for i, lhs := range node.Lhs {
				if name, ok := lhs.(*ast.Ident); ok && name.Name == "fs" && i < len(node.Rhs) {
					allowed[node.Rhs[i]] = true
				}
			}
		case *ast.ValueSpec:
			for i, name := range node.Names {
				if name.Name == "fs" && i < len(node.Values) {
					allowed[node.Values[i]] = true
				}
			}
		}
		return true
	})
	var err error
	ast.Inspect(file, func(node ast.Node) bool {
		if function, ok := node.(*ast.FuncType); ok && err == nil && function.Params != nil {
			for _, parameter := range function.Params.List {
				pointer, ok := parameter.Type.(*ast.StarExpr)
				if !ok {
					continue
				}
				flagSet := false
				switch typ := pointer.X.(type) {
				case *ast.SelectorExpr:
					if receiver, ok := typ.X.(*ast.Ident); ok {
						flagSet = receiver.Name == flagPackage && typ.Sel.Name == "FlagSet"
					}
				case *ast.Ident:
					flagSet = flagPackage == "." && typ.Name == "FlagSet"
				}
				if flagSet {
					for _, name := range parameter.Names {
						if name.Name != "fs" {
							err = fmt.Errorf("%s: *flag.FlagSet parameter must be named fs for help flag generation", positions.Position(name.Pos()))
							return false
						}
					}
				}
			}
		}
		call, ok := node.(*ast.CallExpr)
		if !ok || err != nil {
			return true
		}
		constructor := false
		switch function := call.Fun.(type) {
		case *ast.SelectorExpr:
			if receiver, ok := function.X.(*ast.Ident); ok {
				constructor = receiver.Name == flagPackage && function.Sel.Name == "NewFlagSet"
			}
		case *ast.Ident:
			constructor = flagPackage == "." && function.Name == "NewFlagSet"
		}
		if constructor && !allowed[call] {
			err = fmt.Errorf("%s: flag.NewFlagSet must be assigned directly to fs for help flag generation", positions.Position(call.Pos()))
		}
		return true
	})
	return err
}

func expressionType(expr ast.Expr, types map[string]ast.Expr) string {
	switch value := expr.(type) {
	case *ast.UnaryExpr:
		return expressionType(value.X, types)
	case *ast.CompositeLit:
		if name, ok := value.Type.(*ast.Ident); ok {
			return name.Name
		}
	case *ast.Ident:
		if value.Obj == nil {
			return ""
		}
		switch decl := value.Obj.Decl.(type) {
		case *ast.ValueSpec:
			if name, ok := decl.Type.(*ast.Ident); ok {
				return name.Name
			}
		case *ast.AssignStmt:
			for i, lhs := range decl.Lhs {
				if id, ok := lhs.(*ast.Ident); ok && id.Name == value.Name && i < len(decl.Rhs) {
					return expressionType(decl.Rhs[i], types)
				}
			}
		}
	case *ast.SelectorExpr:
		if structure, ok := types[expressionType(value.X, types)].(*ast.StructType); ok {
			for _, field := range structure.Fields.List {
				for _, name := range field.Names {
					if name.Name == value.Sel.Name {
						if typ, ok := field.Type.(*ast.Ident); ok {
							return typ.Name
						}
					}
				}
			}
		}
	}
	return ""
}
